# Generated by Django 5.2.17 on 2026-09-04 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_size', models.CharField(max_length=32)),
                ('media_type', models.CharField(max_length=32)),
                ('color_mode', models.CharField(max_length=16)),
                ('print_quality', models.CharField(max_length=16)),
                ('price_per_page', models.IntegerField(help_text='Centavos per printed side', validators=[django.core.validators.MinValueValidator(1)])),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-effective_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('media_size', 'media_type', 'color_mode', 'print_quality'), name='unique_price_rule_combination')],
            },
        ),
    ]
