# Generated by Django 5.2.17 on 2026-10-03 01:29

import os

from django.db import migrations, models


def seed_from_env(apps, schema_editor):
    """Seed the singleton from the legacy env vars so quotes are identical at cutover.

    DUPLEX_DISCOUNT_FACTOR / MIN_PARTIAL_PERCENT were read from the environment
    until this migration; the 500-centavo fallback was hardcoded in
    quotation.compute_quote. After this row exists the DB is the single source
    of truth and the env vars are ignored (they remain in settings.py /
    docker-compose.yml only as documentation of the historical defaults).
    """
    PricingSettings = apps.get_model("pricing", "PricingSettings")
    if PricingSettings.objects.filter(pk=1).exists():
        return
    try:
        duplex = float(os.getenv("DUPLEX_DISCOUNT_FACTOR", "0.90"))
    except (TypeError, ValueError):
        duplex = 0.90
    try:
        min_partial = int(os.getenv("MIN_PARTIAL_PERCENT", "50"))
    except (TypeError, ValueError):
        min_partial = 50
    PricingSettings.objects.create(
        pk=1,
        duplex_discount_factor=duplex,
        min_partial_percent=min_partial,
        fallback_price_per_side=500,
    )


def drop_settings(apps, schema_editor):
    apps.get_model("pricing", "PricingSettings").objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplex_discount_factor', models.FloatField(default=0.9, help_text='Multiplier applied to the per-side price of double-sided jobs (0.0-1.0).')),
                ('min_partial_percent', models.PositiveSmallIntegerField(default=50, help_text='Smallest allowed down payment, as a percentage of the subtotal.')),
                ('fallback_price_per_side', models.PositiveIntegerField(default=500, help_text='Centavos per printed side when no price rule matches.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_from_env, drop_settings),
    ]
