# Generated by Django 5.2.17 on 2026-09-04 19:48

import apps.orders.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=128)),
                ('guest_contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('facebook', 'Facebook Messenger')], max_length=16)),
                ('guest_contact_value', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('pending_review', 'Pending Review'), ('revision_requested', 'Revision Requested'), ('approved_queued', 'Approved / Queued'), ('printing', 'Printing'), ('on_hold', 'On Hold - Printer Issue'), ('printed_ready', 'Printed - Ready for Pickup'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=24)),
                ('payment_type', models.CharField(blank=True, choices=[('full', 'Full payment'), ('partial', 'Partial / down payment')], max_length=16)),
                ('subtotal', models.PositiveIntegerField(default=0, help_text='Centavos')),
                ('amount_paid', models.PositiveIntegerField(default=0, help_text='Centavos')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes, never shown to clients')),
                ('revision_note', models.TextField(blank=True, help_text='Sent to the client when a revision is requested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.orders.models.order_file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('edited_file', models.FileField(blank=True, null=True, upload_to=apps.orders.models.order_edited_upload_to)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF document'), ('image', 'Image')], max_length=8)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('edit_actions', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Order status histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_size', models.CharField(default='ps_a4', max_length=32)),
                ('media_type', models.CharField(default='pt_plainpaper', max_length=32)),
                ('color_mode', models.CharField(default='mono', max_length=16)),
                ('sides', models.CharField(default='none', max_length=8)),
                ('print_quality', models.CharField(default='normal', max_length=16)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('borderless', models.BooleanField(default=False)),
                ('source', models.CharField(default='auto', max_length=16)),
                ('reverse_order', models.BooleanField(default=False)),
                ('collate', models.BooleanField(default=True)),
                ('free_text_instructions', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='orders.order')),
                ('order_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='orders.orderfile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
