# Generated by Django 5.2.17 on 2026-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('qrph', 'QR Ph (online)'), ('pickup', 'Pay upon pickup'), ('cash', 'Cash / recorded at the shop')], max_length=16),
        ),
    ]
