# Generated by Django 5.2.17 on 2026-10-01 22:23

import apps.orders.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reprint_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.orders.models.order_final_upload_to),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='page_selection',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderfile',
            name='replaced_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('pending_review', 'Pending Review'), ('revision_requested', 'Revision Requested'), ('approved_queued', 'Approved / Queued'), ('printing', 'Printing'), ('on_hold', 'On Hold - Printer Issue'), ('printed_ready', 'Printed - Ready for Pickup'), ('print_cancelled', 'Cancelled at Printer'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(upload_to=apps.orders.models.order_file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'docx', 'xlsx', 'pptx', 'txt', 'md', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF document'), ('image', 'Image'), ('document', 'Office / text document')], max_length=8),
        ),
    ]
