# Generated by Django 5.2.17 on 2026-10-03 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_reprint_count_orderfile_final_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OrderFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='orders/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF document'), ('image', 'Image'), ('document', 'Office / text document')], max_length=16)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('edit_actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orders.orderfile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_version_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version_number'],
                'constraints': [models.UniqueConstraint(fields=('order_file', 'version_number'), name='unique_file_version_number')],
            },
        ),
    ]
