# Generated by Django 5.2.17 on 2026-10-03 15:10

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderfile_current_version_orderfileversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfileversion',
            name='file',
            field=models.FileField(upload_to=apps.orders.models.order_file_version_upload_to),
        ),
    ]
