# Generated by Django 5.2.17 on 2026-10-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderfileversion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='rendered_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printspecification',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10),
        ),
    ]
