# Generated by Django 5.2.17 on 2026-09-04 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epson_job_id', models.CharField(blank=True, max_length=64)),
                ('upload_uri', models.CharField(blank=True, max_length=512)),
                ('printer_name', models.CharField(blank=True, max_length=128)),
                ('print_mode', models.CharField(blank=True, max_length=16)),
                ('print_settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted to Epson'), ('executed', 'Executed'), ('printing', 'Printing'), ('completed', 'Completed'), ('on_hold', 'On Hold - Printer Issue'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='created', max_length=16)),
                ('epson_status', models.CharField(blank=True, max_length=32)),
                ('pages_printed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='orders.order')),
                ('order_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='orders.orderfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
