# Generated by Django 5.2.17 on 2026-10-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpsonCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(blank=True)),
                ('pending_state', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Epson credential',
                'verbose_name_plural': 'Epson credential',
            },
        ),
    ]
