# Generated by Django 5.2.17 on 2026-10-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_epsoncredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='is_reprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printjob',
            name='pages_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
