# Generated by Django 5.2.17 on 2026-10-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('approver', 'Approver (print orders)'), ('admin', 'Admin / Staff')], default='client', max_length=16),
        ),
    ]
