from django.urls import path

from .views import (
    AdminOrderActionView,
    AdminOrderDetailView,
    AdminOrderFilePagesView,
    AdminOrderFileReplaceView,
    AdminOrderListView,
    AdminOrderNotesView,
    AdminOrderSpecView,
    AdminResubmitView,
    OrderCreateView,
    OrderDetailView,
    OrderEstimateView,
    OrderFileEditView,
    OrderFilePreviewView,
    OrderFileReuploadView,
    OrderFileTextPreviewView,
    OrderListView,
    OrderResubmitView,
    QuoteView,
    TrackOrderView,
)

urlpatterns = [
    path("orders/", OrderCreateView.as_view(), name="order-create"),
    path("orders/quote/", QuoteView.as_view(), name="order-quote"),
    path("orders/estimate/", OrderEstimateView.as_view(), name="order-estimate"),
    path("orders/mine/", OrderListView.as_view(), name="order-list"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path("orders/<int:order_pk>/files/<int:file_pk>/edit/", OrderFileEditView.as_view(), name="order-file-edit"),
    path("orders/<int:order_pk>/files/<int:file_pk>/preview/", OrderFilePreviewView.as_view(), name="order-file-preview"),
    path("orders/<int:order_pk>/files/<int:file_pk>/contents/",
         OrderFileTextPreviewView.as_view(), name="order-file-contents"),
    path("orders/<int:order_pk>/files/<int:file_pk>/reupload/",
         OrderFileReuploadView.as_view(), name="order-file-reupload"),
    path("orders/<int:pk>/resubmit/", OrderResubmitView.as_view(), name="order-resubmit"),
    path("track/<str:tracking_id>/", TrackOrderView.as_view(), name="order-track"),
    # admin
    path("admin/orders/", AdminOrderListView.as_view(), name="admin-order-list"),
    path("admin/orders/<int:pk>/", AdminOrderDetailView.as_view(), name="admin-order-detail"),
    path("admin/orders/<int:pk>/actions/<str:action>/", AdminOrderActionView.as_view(), name="admin-order-action"),
    path("admin/orders/<int:pk>/notes/", AdminOrderNotesView.as_view(), name="admin-order-notes"),
    path("admin/orders/<int:order_pk>/specs/<int:spec_pk>/", AdminOrderSpecView.as_view(), name="admin-order-spec"),
    path("admin/orders/<int:order_pk>/files/<int:file_pk>/pages/",
         AdminOrderFilePagesView.as_view(), name="admin-order-file-pages"),
    path("admin/orders/<int:order_pk>/files/<int:file_pk>/replace/",
         AdminOrderFileReplaceView.as_view(), name="admin-order-file-replace"),
    path("admin/orders/<int:pk>/resubmit/", AdminResubmitView.as_view(), name="admin-order-resubmit"),
]
