# Generated by Django 5.2.17 on 2026-09-04 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payment_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.PositiveIntegerField(help_text='Centavos charged for this intent')),
                ('method', models.CharField(default='qrph', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Awaiting scan'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('qr_image_url', models.TextField(blank=True)),
                ('checkout_expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refund_status', models.CharField(blank=True, max_length=32)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
