# Generated by Django 5.2.17 on 2026-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_pay_on_pickup', models.BooleanField(default=True, help_text='Customers may choose to settle the balance when they pick up their printout.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
