# Generated by Django 5.2.7 on 2026-10-09 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderfile_rendered_by_admin_and_more'),
        ('payments', '0002_paymentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], max_length=16)),
                ('amount', models.PositiveIntegerField(help_text='Centavos; kind decides the sign (+payment / −refund).')),
                ('method', models.CharField(default='qrph', max_length=16)),
                ('tracking_id', models.CharField(db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_entries', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_entries', to='payments.payment')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'kind'), name='unique_sales_entry_per_payment_and_kind')],
            },
        ),
    ]
